This is a test for the BaseGeometry class in order to check the method integer_validator.

    >>> BaseGeometry = __import__('7-base_geometry').BaseGeometry
	>>> bg = BaseGeometry()
    >>> bg.integer_validator("my_int", 12)
    >>> bg.integer_validator("width", 89)
	>>> bg.integer_validator("30", 20)
	>>> bg.integer_validator("my_int", 12590398)

Errors:
	>>> bg.integer_validator("name", "John")
	Traceback (most recent call last):
	...
	TypeError: name must be an integer
    >>> bg.integer_validator("Zero", 0)
    Traceback (most recent call last):
    ...
    ValueError: Zero must be greater than 0
    >>> bg.integer_validator("Negative", -100)
    Traceback (most recent call last):
    ...
    ValueError: Negative must be greater than 0
    >>> bg.integer_validator("String", "hello")
    Traceback (most recent call last):
    ...
    TypeError: String must be an integer
	>>> bg.integer_validator("None", None)
	Traceback (most recent call last):
	...
	TypeError: None must be an integer
	>>> bg.integer_validator("Float", 4.67)
	Traceback (most recent call last):
	...
	TypeError: Float must be an integer
	>>> bg.integer_validator()
	Traceback (most recent call last):
	...
	TypeError: integer_validator() missing 2 required positional arguments: 'name' and 'value'
	>>> bg.integer_validator(None)
	Traceback (most recent call last):
	...
	TypeError: integer_validator() missing 1 required positional argument: 'value'
	>>> bg.integer_validator("Nothing")
	Traceback (most recent call last):
	...
	TypeError: integer_validator() missing 1 required positional argument: 'value'
	>>> bg.integer_validator(hi, 20)
	Traceback (most recent call last):
	...
	NameError: name 'hi' is not defined
	>>> bg.integer_validator("my_int", NaN)
	Traceback (most recent call last):
	...
	NameError: name 'NaN' is not defined
	>>> bg.integer_validator("my_int", 12590398, 20339)
	Traceback (most recent call last):
	...
	TypeError: integer_validator() takes 3 positional arguments but 4 were given
	>>> bg.area()
	Traceback (most recent call last):
	...
	Exception: area() is not implemented
	>>> bg.area(3)
	Traceback (most recent call last):
	...
	TypeError: area() takes 1 positional argument but 2 were given
	>>> bg.integer_validator("my_int", [2])
	Traceback (most recent call last):
	...
	TypeError: my_int must be an integer
